# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TestProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # Pods for TestProject
  
  pod 'SDWebImage'

end
